# Site settings
title: Baumartig
email: the_wizard@gmx.li
description: > # this means to ignore newlines until "baseurl:"
  On this page you can find informations to my github projects.
url: "http://baumartig.de" # the base hostname & protocol for your site
github_username: "baumartig"

# Build settings
markdown: kramdown
